name: toast_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  flutter_svg: ^0.22.0
  flutter_card_swipper: ^0.4.0
  auto_size_text: ^3.0.0-nullsafety.0
  im_stepper: ^0.1.3
  google_maps_flutter: ^2.0.3
  geolocator: ^7.2.0+1
  geocoding: ^2.0.0
#  geocoder: ^0.2.1

  shimmer: ^2.0.0
  dio: ^4.0.0
  freezed_annotation: ^0.14.2
  dartz: ^0.10.0-nullsafety.2
  direct_select_flutter: ^1.1.1
  multi_select_flutter: ^4.0.0
  meta:
  lottie: ^1.0.1
  url_launcher: ^6.0.6
  group_button: ^2.2.2
  like_button: ^2.0.2
  badges: ^2.0.1

  flutter_chat_ui: ^1.1.4
  file_picker: ^3.0.2+2
  image_picker: ^0.7.5+3
  mime: ^1.0.0
  open_file: ^3.2.1
  uuid: ^3.0.4
  fluttertoast: ^8.0.7
  flutter:
    sdk: flutter

dev_dependencies:
  freezed: ^0.14.2
  json_serializable: ^4.1.3
  build_runner: ^2.0.4
  flutter_test:
    sdk: flutter
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/home/
    - assets/images/special_order/
    - assets/images/bottom_navigation/
    - assets/images/shopping_cart/
    - assets/images/sign_in/
    - assets/lottie/
    - assets/test/
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
